### ISSUE TITLE
Extended zip code handling

### ISSUE THREAD

**Issue by mcnelson** [monicao/zip-code-info#3]
It would be nice if ZipCodeInfo could handle extended zips.

``` ruby
[2] pry(main)> ZipCodeInfo.instance.state_for("12345")
=> "NY"
[3] pry(main)> ZipCodeInfo.instance.state_for("12345-6789")
=> false
```

If I find time, I'll open a PR, but just to get the issue out there!

**Comment by monicao** [comment]
Thanks for pointing this out! Didn't know about extended zip codes.
